### ISSUE TITLE
Invalid allow_anonymous value

### ISSUE THREAD

**Issue by han94ros** [eclipse-mosquitto/mosquitto#2330]
I am trying to run the following command. 

docker run -p 1883:1883 --name mosquitto -v "/c/Users/Dell PC Roshan/stabilizer"/mosquitto.conf:/mosquitto/config/mosquitto.conf -v /mosquitto/data -v /mosquitto/log eclipse-mosquitto:2

and I am getting the following error. 

33022744: Error: Invalid allow_anonymous value (true
1633022744: Error found at /mosquitto/config/mosquitto.conf:1.

Could someone please advise me.

**Comment by CedricGoby** [comment]
Same here.

The mosquitto service in the compose file :

```
mosquitto:
    container_name: my-mosquitto
    image: eclipse-mosquitto:latest
    user: '1000'
    depends_on:
      - influxdb
    labels:
      - traefik.http.routers.mosquitto.rule=Host(`mosquitto.domain.tld`)
      - traefik.http.routers.mosquitto.tls=true
      - traefik.http.routers.mosquitto.tls.certresolver=lets-encrypt
      - traefik.port=1883
    networks:
      - web
    ports:
      - "1883:1883"
      - "9001:9001"
    links:
      - influxdb:influxdb
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /etc/localtime:/etc/localtime:ro
    restart: always
```


mosquitto.conf : 

```
allow_anonymous true
listener 1883
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
```
